### ISSUE TITLE
[Request] Delugia Code

### ISSUE THREAD

**Issue by rashil2000** [sumo300/chocolatey-nerd-fonts#3]
This is an up-to-date, better and more supported version of Cascadia Code than ryanoasis's. The repo is here https://github.com/adam7/delugia-code and downloads are here https://github.com/adam7/delugia-code/releases

For reference, Scoop [already has](https://github.com/matthewjberger/scoop-nerd-fonts/search?q=delugia) Delugia Code.

**Comment by sumo300** [comment]
@rashil2000 I started working on this.  I am creating each zip in the release as their own Chocolatey packages.  As new releases are published, new chocolatey packages will be pushed automatically.  Let me know if this is an acceptable approach or if you feel all of the delugia zips should be packaged as a single installable font package.

**Comment by rashil2000** [comment]
Hey, thanks for the update!

I personally prefer each zip as its own package (offers more flexibility), but I'm not aware of how most people use it.

Feel free to publish them as you prefer 😅

**Comment by sumo300** [comment]
@rashil2000 Wasn't sure if you saw, but all 5 Delugia fonts have been packaged and released to Chocolatey.org.

**Comment by rashil2000** [comment]
Awesome!

I have updated the upstream issue with this news :)
