### ISSUE TITLE
Gohu package fails to install any font

### ISSUE THREAD

**Issue by sumo300** [sumo300/chocolatey-nerd-fonts#6]
https://gist.github.com/choco-bot/ee67aa0a3ef9aa1aad7561bbbab9d9b0

**Comment by sumo300** [comment]
Issue is that this font includes variations of the same fonts in subdirectories.  The installer does not expect fonts to be in subdirectories.

**Comment by Finii** [comment]
Wouldn't it make sense to add `-recurse` everywhere? First saw it with `Delugia`.

It does not hurt on flat directorys as we have almosty everywhere right now, but also works with trees... See also https://github.com/ryanoasis/nerd-fonts/issues/919

I also (always) wonder why people install all fonts (Windows Compat AND normal); even on Linux, that does not make any sense.

By the way, even on Windows I have never ever used the Windows Compat versions and never had any issue. Do you know anything in this regard? Would be good if we could finally drop the Windows Compat versions (that just differ in some name properties), halving everything.
